spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mypass112233
    url: jdbc:mysql://127.0.0.1:3306/Mall?characterEncoding=utf-8&useSSL=false&serverTimezone=PST
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    addresses: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    控制台log配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml